collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.04351531993597746
  brandStrength: 0.2190682806540281
  rhythmicContrast: 0.5152033432386816
  brandColors:
    - '#E8E595'
    - '#D0A825'
    - '#40627C'
    - '#26393D'
    - '#FFFAE4'
  lightness: 0.5800462937913835
typography_spectrum: 0.3979592
layout_spectrum: 0.7803437
name: Sincerely J
