collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5150304266717285
  brandStrength: 0.3585020510945469
  rhythmicContrast: 0.1843955486547202
  brandColors:
    - '#F2F4E7'
    - '#F48100'
    - '#004F81'
    - '#8B0109'
    - '#00945E'
  lightness: 0.709397301543504
typography_spectrum: 0.4902497665025294
layout_spectrum: 0.4455750994384289
name: Sincerely J
